# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ruoJ2UBAz1Q0ZwUndmzcTMS0HqKdF17c
"""

pip install fuzzywuzzy

pip install python-Levenshtein

from fuzzywuzzy import fuzz
from fuzzywuzzy import process

class Boss:
    def __init__(self, name, surname, email, number, age, experience, field, city, position, skills_knowledges):
        self.name = name
        self.surname = surname
        self.email = email
        self.number = number
        self.age = age
        self.experience = experience
        self.field = field
        self.city = city
        self.position = position
        self.skills_knowledges = skills_knowledges
        

class Person(Boss):
    pass


person1 = Person('Balqabaq', 'Kelemov', 'balqabaqk@gmail.com', '+994509999999', '41', '5', 'engineering', 'Baku', 'electrical engineer', 'pyhton')

boss1 = Boss('Xiyar', 'Ishverenov', 'xiyarmmc@gmail.com', '+994553333333', '61', '4', 'engineer', 'Baki', 'mechanic',  'python programming')

boss1_list = []
person1_list = []
boss1_list.extend([boss1.experience, boss1.field, boss1.city, boss1.position, boss1.skills_knowledges])
person1_list.extend([person1.experience, person1.field, person1.city, person1.position, person1.skills_knowledges])

def get_matches(query, choices, limit = 1):
  results = process.extract(query, choices, limit=limit)
  return results

matchingField_list = get_matches(boss1.field, person1_list)
matchingCity_list = get_matches(boss1.city, person1_list)
matchingPosition_list = get_matches(boss1.position, person1_list)
matchingSkills_list = get_matches(boss1.skills_knowledges, person1_list)

m1 = matchingField_list[0][1]
m2 = matchingCity_list[0][1]
m3 = matchingPosition_list[0][1]
m4 = matchingSkills_list[0][1]

print(m1,m2,m3,m4)

if (m1 + m2 + m3 + m4) / 4 > 81:
  print("Candidate is matched")
else:
  print("Candidate is not matched")

